#!/bin/sh 

DIR=`cd ${0%*/*};pwd`
\rm -rf ../autom4te.cache
\rm -rf ../aclocal.m4
\rm -f missing install-sh depcomp mkinstalldirs ltmain.sh config.sub config.guess
# make sure autoconf is up-to-date
ac_ver=`autoconf --version | head -1 | awk '{print $NF}'`
ac_maj=`echo $ac_ver|sed 's/\..*//'`
ac_min=`echo $ac_ver|sed 's/.*\.//'`
if [[ $ac_maj < 2 ]]; then 
    echo "autoconf version is too old:$ac_maj.$ac_min < required 2.59"
    exit
fi
if [[ $ac_maj = 2 && $ac_min < 59 ]]; then 
    echo "autoconf version is too old:$ac_maj.$ac_min < required 2.59"
    exit
fi
# make sure automake is up-to-date
am_ver=`automake --version | head -1 | awk '{print $NF}'`
am_maj=`echo $am_ver|sed 's/\..*//'`
am_min=`echo $am_ver|sed 's/.*\.\([^\.]*\)\..*/\1/'`
am_sub=`echo $am_ver|sed 's/.*\.//'`
if [[ $am_maj < 1 ]]; then 
    echo Min automake version is 1.9.3
    exit
fi
if [[ $am_maj = 1 && $am_min < 9 ]]; then 
    echo "automake version is too old:$am_maj.$am_min.$am_sub < required 1.9.3"
    exit
fi
if [[ $am_maj = 1 && $am_min = 9 && $am_sub < 3 ]]; then 
    echo "automake version is too old:$am_maj.$am_min.$am_sub < required 1.9.3"
    exit
fi

aclocal -I config
libtoolize --automake
automake --add-missing --gnu
autoconf
